default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-cp9kf7v109ks73aa9eb0-a.oregon-postgres.render.com


development:
  <<: *default
  database: nobilis
  username: nobilis_user
  password: 7u23g0OeZNJdTwAmjxqhiBsL6GHQbB9G

test:
  <<: *default
  database: starter_online_backend_test

production:
  <<: *default
  database: nobilis
  username: nobilis_user
  password: 7u23g0OeZNJdTwAmjxqhiBsL6GHQbB9G
