default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-cq8julij1k6c73cmp3qg-a.oregon-postgres.render.com


development:
  <<: *default
  database: nobilis_6d4e
  username: nobilis_6d4e_user
  password: RUBxkGXxW6IoLkuT7S3pIlyOXIFa5lxK

test:
  <<: *default
  database: starter_online_backend_test

production:
  <<: *default
  database: nobilis_6d4e
  username: nobilis_6d4e_user
  password: RUBxkGXxW6IoLkuT7S3pIlyOXIFa5lxK
